// Generated By: Claude Code (Claude Opus 4.6)
// Banner registry — each entry defines a blockable banner.
// To add a new banner, add an entry to this array.

const BANNERS = Object.freeze([
  Object.freeze({
    id: "atlassian-cloud-welcome",
    name: "Atlassian Cloud Welcome Banner",
    description: "\"Welcome to Atlassian Cloud! To report issues, raise a support ticket here.\"",
    defaultEnabled: true,
    selector: '[data-ssr-placeholder="announcement-banner"]',
    textMatch: "Welcome to Atlassian Cloud"
  })
]);

const BANNER_IDS = Object.freeze(BANNERS.map(function (b) { return b.id; }));

function getDefaultStates() {
  var defaults = {};
  for (var i = 0; i < BANNERS.length; i++) {
    defaults[BANNERS[i].id] = BANNERS[i].defaultEnabled;
  }
  return defaults;
}

var HIDDEN_ATTR = "data-banner-blocker-hidden";

function matchesBanner(el, banner) {
  if (banner.textMatch && !el.textContent.includes(banner.textMatch)) {
    return false;
  }
  return true;
}

var BANNER_HEIGHT_PATTERN = /--(?:bannerHeight|n_bnrM)\s*:/;

function hideBanner(el) {
  el.setAttribute(HIDDEN_ATTR, "true");
  // Remove <style> tags in the banner's parent that set layout height variables.
  // Atlassian reserves banner space via CSS custom properties (--bannerHeight, --n_bnrM)
  // injected in <style> siblings — display:none alone leaves a blank gap.
  // Run every time (not just first hide) because Atlassian's SPA re-injects them.
  var parent = el.parentElement;
  if (parent) {
    var styles = parent.querySelectorAll("style");
    for (var i = 0; i < styles.length; i++) {
      if (BANNER_HEIGHT_PATTERN.test(styles[i].textContent)) {
        parent.removeChild(styles[i]);
      }
    }
  }
}

function showBanner(el) {
  if (el.hasAttribute(HIDDEN_ATTR)) {
    el.removeAttribute(HIDDEN_ATTR);
  }
}
