// Generated By: Claude Code (Claude Opus 4.6)
// Banner registry — each entry defines a blockable banner.
// To add a new banner, add an entry to this array.

const BANNERS = Object.freeze([
  Object.freeze({
    id: "atlassian-cloud-welcome",
    name: "Atlassian Cloud Welcome Banner",
    description: "\"Welcome to Atlassian Cloud! To report issues, raise a support ticket here.\"",
    defaultEnabled: true,
    selector: '[data-testid="banner-container"]',
    textMatch: "Welcome to Atlassian Cloud"
  })
]);

const BANNER_IDS = Object.freeze(BANNERS.map(function (b) { return b.id; }));

function getDefaultStates() {
  var defaults = {};
  for (var i = 0; i < BANNERS.length; i++) {
    defaults[BANNERS[i].id] = BANNERS[i].defaultEnabled;
  }
  return defaults;
}

var HIDDEN_ATTR = "data-banner-blocker-hidden";

function matchesBanner(el, banner) {
  if (banner.textMatch && !el.textContent.includes(banner.textMatch)) {
    return false;
  }
  return true;
}

function hideBanner(el) {
  if (!el.hasAttribute(HIDDEN_ATTR)) {
    el.setAttribute(HIDDEN_ATTR, "true");
  }
}

function showBanner(el) {
  if (el.hasAttribute(HIDDEN_ATTR)) {
    el.removeAttribute(HIDDEN_ATTR);
  }
}
