// Generated By: Claude Code (Claude Opus 4.6)
// Content script — detects and hides banners based on user settings.
/* global BANNERS, BANNER_IDS, HIDDEN_ATTR, getDefaultStates, matchesBanner, hideBanner, showBanner */

(function () {
  "use strict";

  var TAG = "[Banner Blocker]";

  if (typeof BANNERS === "undefined") {
    throw new Error("banners.js must be loaded before content.js");
  }

  console.log(TAG, "Content script loaded on", location.hostname);

  var blockingEnabled = {};

  function processBanners() {
    for (var i = 0; i < BANNERS.length; i++) {
      var banner = BANNERS[i];
      var elements;
      try {
        elements = document.querySelectorAll(banner.selector);
      } catch (e) {
        console.warn(TAG, "Invalid selector for", banner.id, ":", banner.selector);
        continue;
      }
      for (var j = 0; j < elements.length; j++) {
        var el = elements[j];
        if (!matchesBanner(el, banner)) continue;
        if (blockingEnabled[banner.id]) {
          if (!el.hasAttribute(HIDDEN_ATTR)) {
            console.log(TAG, "Hiding", banner.id);
          }
          hideBanner(el);
        } else {
          if (el.hasAttribute(HIDDEN_ATTR)) {
            console.log(TAG, "Showing", banner.id);
          }
          showBanner(el);
        }
      }
    }
  }

  // Debounce to avoid excessive processing during SPA navigation
  var debounceTimer = null;
  function debouncedProcess() {
    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(processBanners, 100);
  }

  // Load saved states and start observing
  chrome.storage.local.get(BANNER_IDS, function (stored) {
    if (chrome.runtime.lastError) {
      console.warn(TAG, "Storage error, using defaults:", chrome.runtime.lastError.message);
      blockingEnabled = getDefaultStates();
    } else {
      blockingEnabled = Object.assign({}, getDefaultStates(), stored);
      console.log(TAG, "Loaded states:", JSON.stringify(blockingEnabled));
    }
    processBanners();

    var observer = new MutationObserver(debouncedProcess);
    observer.observe(document.body, { childList: true, subtree: true });
    console.log(TAG, "MutationObserver active");
  });

  // React to toggle changes from popup without page reload
  chrome.storage.onChanged.addListener(function (changes) {
    for (var key in changes) {
      if (BANNER_IDS.indexOf(key) === -1) continue;
      if (changes[key].newValue !== undefined) {
        console.log(TAG, "Toggle", key, "->", changes[key].newValue);
        blockingEnabled[key] = changes[key].newValue;
      }
    }
    processBanners();
  });
})();
