// Generated By: Claude Code (Claude Opus 4.6)
// Content script — detects and hides banners based on user settings.
/* global BANNERS, BANNER_IDS, HIDDEN_ATTR, getDefaultStates, matchesBanner, hideBanner, showBanner */

(function () {
  "use strict";

  if (typeof BANNERS === "undefined") {
    throw new Error("banners.js must be loaded before content.js");
  }

  var blockingEnabled = {};

  // Inject a style rule for hiding — more resilient than inline style manipulation
  var style = document.createElement("style");
  style.textContent = "[" + HIDDEN_ATTR + "] { display: none !important; }";
  document.head.appendChild(style);

  function processBanners() {
    for (var i = 0; i < BANNERS.length; i++) {
      var banner = BANNERS[i];
      var elements;
      try {
        elements = document.querySelectorAll(banner.selector);
      } catch (e) {
        continue;
      }
      for (var j = 0; j < elements.length; j++) {
        var el = elements[j];
        if (!matchesBanner(el, banner)) continue;
        if (blockingEnabled[banner.id]) {
          hideBanner(el);
        } else {
          showBanner(el);
        }
      }
    }
  }

  // Debounce to avoid excessive processing during SPA navigation
  var debounceTimer = null;
  function debouncedProcess() {
    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(processBanners, 100);
  }

  // Load saved states and start observing
  chrome.storage.local.get(BANNER_IDS, function (stored) {
    if (chrome.runtime.lastError) {
      blockingEnabled = getDefaultStates();
    } else {
      blockingEnabled = Object.assign({}, getDefaultStates(), stored);
    }
    processBanners();

    var observer = new MutationObserver(debouncedProcess);
    observer.observe(document.body, { childList: true, subtree: true });
  });

  // React to toggle changes from popup without page reload
  chrome.storage.onChanged.addListener(function (changes) {
    for (var key in changes) {
      if (BANNER_IDS.indexOf(key) === -1) continue;
      if (changes[key].newValue !== undefined) {
        blockingEnabled[key] = changes[key].newValue;
      }
    }
    processBanners();
  });
})();
