# Generated By: Claude Code (Claude Opus 4.6)

.PHONY: all check install-dev clean test coverage help

all: check  ## Run all checks (default)

check: test coverage  ## Run all validation

install-dev:  ## Install dependencies
	npm install

clean:  ## Remove generated files
	rm -rf node_modules/ coverage/

test: install-dev  ## Run tests
	npm test

coverage: install-dev  ## Run tests with coverage
	npx vitest run --coverage

help:  ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'

.DEFAULT_GOAL := all
