// Generated By: Claude Code (Claude Opus 4.6)
// Popup logic — renders toggles and persists state.
/* global BANNERS, BANNER_IDS, getDefaultStates */

(function () {
  "use strict";

  var TAG = "[Banner Blocker]";

  if (typeof BANNERS === "undefined") {
    throw new Error("banners.js must be loaded before popup.js");
  }

  var list = document.getElementById("banner-list");

  function createBannerItem(banner, enabled) {
    var item = document.createElement("div");
    item.className = "banner-item";
    item.setAttribute("role", "listitem");

    var info = document.createElement("div");
    info.className = "banner-info";

    var name = document.createElement("div");
    name.className = "banner-name";
    name.textContent = banner.name;

    var desc = document.createElement("div");
    desc.className = "banner-desc";
    desc.textContent = banner.description;

    info.appendChild(name);
    info.appendChild(desc);

    var toggle = document.createElement("label");
    toggle.className = "toggle";

    var input = document.createElement("input");
    input.type = "checkbox";
    input.checked = enabled;
    input.setAttribute("aria-label", "Block " + banner.name);
    input.addEventListener("change", function () {
      var update = {};
      update[banner.id] = input.checked;
      console.log(TAG, "Toggle", banner.id, "->", input.checked);
      chrome.storage.local.set(update, function () {
        if (chrome.runtime.lastError) {
          console.warn(TAG, "Failed to save", banner.id, ":", chrome.runtime.lastError.message);
          input.checked = !input.checked;
        }
      });
    });

    var slider = document.createElement("span");
    slider.className = "slider";

    toggle.appendChild(input);
    toggle.appendChild(slider);

    item.appendChild(info);
    item.appendChild(toggle);
    return item;
  }

  function renderBanners(states) {
    list.replaceChildren();
    for (var i = 0; i < BANNERS.length; i++) {
      var banner = BANNERS[i];
      var enabled = states[banner.id] !== undefined ? states[banner.id] : banner.defaultEnabled;
      list.appendChild(createBannerItem(banner, enabled));
    }
    console.log(TAG, "Rendered", BANNERS.length, "banner toggles");
  }

  chrome.storage.local.get(BANNER_IDS, function (stored) {
    var states;
    if (chrome.runtime.lastError) {
      console.warn(TAG, "Storage error, using defaults:", chrome.runtime.lastError.message);
      states = getDefaultStates();
    } else {
      states = Object.assign({}, getDefaultStates(), stored);
    }
    renderBanners(states);
  });
})();
