// Generated By: Claude Code (Claude Opus 4.6)
import { describe, it, expect } from "vitest";

describe("BANNERS registry", function () {
  it("has required fields on every entry", function () {
    var required = ["id", "name", "description", "defaultEnabled", "selector", "textMatch"];
    for (var i = 0; i < BANNERS.length; i++) {
      var banner = BANNERS[i];
      for (var j = 0; j < required.length; j++) {
        expect(banner).toHaveProperty(required[j]);
      }
    }
  });

  it("has no duplicate IDs", function () {
    var ids = {};
    for (var i = 0; i < BANNERS.length; i++) {
      expect(ids[BANNERS[i].id]).toBeUndefined();
      ids[BANNERS[i].id] = true;
    }
  });

  it("has at least one banner", function () {
    expect(BANNERS.length).toBeGreaterThan(0);
  });
});

describe("BANNER_IDS", function () {
  it("contains all banner IDs", function () {
    for (var i = 0; i < BANNERS.length; i++) {
      expect(BANNER_IDS).toContain(BANNERS[i].id);
    }
    expect(BANNER_IDS.length).toBe(BANNERS.length);
  });
});

describe("getDefaultStates", function () {
  it("returns defaultEnabled for each banner", function () {
    var defaults = getDefaultStates();
    for (var i = 0; i < BANNERS.length; i++) {
      expect(defaults[BANNERS[i].id]).toBe(BANNERS[i].defaultEnabled);
    }
  });

  it("returns an object with one key per banner", function () {
    var defaults = getDefaultStates();
    expect(Object.keys(defaults).length).toBe(BANNERS.length);
  });
});

describe("matchesBanner", function () {
  it("returns true when textContent includes textMatch", function () {
    var el = document.createElement("div");
    el.textContent = "Welcome to Atlassian Cloud! More text here.";
    var banner = { textMatch: "Welcome to Atlassian Cloud" };
    expect(matchesBanner(el, banner)).toBe(true);
  });

  it("returns false when textContent does not include textMatch", function () {
    var el = document.createElement("div");
    el.textContent = "Some other banner text";
    var banner = { textMatch: "Welcome to Atlassian Cloud" };
    expect(matchesBanner(el, banner)).toBe(false);
  });

  it("returns true when textMatch is empty", function () {
    var el = document.createElement("div");
    el.textContent = "anything";
    var banner = { textMatch: "" };
    expect(matchesBanner(el, banner)).toBe(true);
  });

  it("returns true when textMatch is undefined", function () {
    var el = document.createElement("div");
    el.textContent = "anything";
    var banner = {};
    expect(matchesBanner(el, banner)).toBe(true);
  });
});

describe("hideBanner", function () {
  it("sets the hidden attribute", function () {
    var el = document.createElement("div");
    hideBanner(el);
    expect(el.hasAttribute(HIDDEN_ATTR)).toBe(true);
    expect(el.getAttribute(HIDDEN_ATTR)).toBe("true");
  });

  it("is idempotent", function () {
    var el = document.createElement("div");
    hideBanner(el);
    hideBanner(el);
    expect(el.getAttribute(HIDDEN_ATTR)).toBe("true");
  });
});

describe("showBanner", function () {
  it("removes the hidden attribute", function () {
    var el = document.createElement("div");
    el.setAttribute(HIDDEN_ATTR, "true");
    showBanner(el);
    expect(el.hasAttribute(HIDDEN_ATTR)).toBe(false);
  });

  it("is a no-op if not hidden", function () {
    var el = document.createElement("div");
    showBanner(el);
    expect(el.hasAttribute(HIDDEN_ATTR)).toBe(false);
  });
});
