// Generated By: Claude Code (Claude Opus 4.6)
// Minimal chrome.storage and chrome.runtime stub for testing.

export function createChromeMock() {
  var store = {};
  var listeners = [];
  var lastError = null;

  var mock = {
    storage: {
      local: {
        get: function (keys, callback) {
          if (lastError) {
            Object.defineProperty(mock.runtime, "lastError", { value: lastError, configurable: true });
            callback({});
            return;
          }
          Object.defineProperty(mock.runtime, "lastError", { value: null, configurable: true });
          var result = {};
          var keyList = Array.isArray(keys) ? keys : (keys === null ? Object.keys(store) : [keys]);
          for (var i = 0; i < keyList.length; i++) {
            if (store[keyList[i]] !== undefined) {
              result[keyList[i]] = store[keyList[i]];
            }
          }
          callback(result);
        },
        set: function (items, callback) {
          if (lastError) {
            Object.defineProperty(mock.runtime, "lastError", { value: lastError, configurable: true });
            if (callback) callback();
            return;
          }
          Object.defineProperty(mock.runtime, "lastError", { value: null, configurable: true });
          var changes = {};
          for (var key in items) {
            changes[key] = { oldValue: store[key], newValue: items[key] };
            store[key] = items[key];
          }
          for (var j = 0; j < listeners.length; j++) {
            listeners[j](changes);
          }
          if (callback) callback();
        }
      },
      onChanged: {
        addListener: function (fn) {
          listeners.push(fn);
        }
      }
    },
    runtime: {
      lastError: null
    }
  };

  return {
    chrome: mock,
    setStore: function (data) { store = Object.assign({}, data); },
    getStore: function () { return Object.assign({}, store); },
    setLastError: function (err) { lastError = err; },
    clearLastError: function () { lastError = null; },
    reset: function () {
      store = {};
      listeners = [];
      lastError = null;
      Object.defineProperty(mock.runtime, "lastError", { value: null, configurable: true });
    }
  };
}
