// Generated By: Claude Code (Claude Opus 4.6)
import { describe, it, expect, beforeEach, vi } from "vitest";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { createChromeMock } from "./chrome-mock.js";

var dir = path.dirname(fileURLToPath(import.meta.url));
var contentSource = fs.readFileSync(path.resolve(dir, "..", "content.js"), "utf-8");

function loadContentScript(chromeMock) {
  globalThis.chrome = chromeMock.chrome;
  // The source is an IIFE — evaluate it directly. Just remove the BANNERS guard
  // since banners.js globals are already loaded via setup.js.
  var adapted = contentSource.replace(/if \(typeof BANNERS[^}]*\}\s*/, "");
  new Function(adapted)();
}

describe("content script", function () {
  var mockHelper;

  beforeEach(function () {
    mockHelper = createChromeMock();
    document.head.innerHTML = "";
    document.body.innerHTML = "";
  });

  it("hides matching banner elements when blocking is enabled", function () {
    var el = document.createElement("div");
    el.setAttribute("data-ssr-placeholder", "announcement-banner");
    el.textContent = "Welcome to Atlassian Cloud! To report issues, raise a support ticket here.";
    document.body.appendChild(el);

    loadContentScript(mockHelper);

    expect(el.hasAttribute("data-banner-blocker-hidden")).toBe(true);
  });

  it("does not hide elements when blocking is disabled", function () {
    mockHelper.setStore({ "atlassian-cloud-welcome": false });

    var el = document.createElement("div");
    el.setAttribute("data-ssr-placeholder", "announcement-banner");
    el.textContent = "Welcome to Atlassian Cloud!";
    document.body.appendChild(el);

    loadContentScript(mockHelper);

    expect(el.hasAttribute("data-banner-blocker-hidden")).toBe(false);
  });

  it("skips elements that do not match textMatch", function () {
    var el = document.createElement("div");
    el.setAttribute("data-ssr-placeholder", "announcement-banner");
    el.textContent = "Some other banner content";
    document.body.appendChild(el);

    loadContentScript(mockHelper);

    expect(el.hasAttribute("data-banner-blocker-hidden")).toBe(false);
  });

  it("uses defaults when storage returns an error", function () {
    mockHelper.setLastError({ message: "storage error" });

    var el = document.createElement("div");
    el.setAttribute("data-ssr-placeholder", "announcement-banner");
    el.textContent = "Welcome to Atlassian Cloud!";
    document.body.appendChild(el);

    loadContentScript(mockHelper);

    expect(el.hasAttribute("data-banner-blocker-hidden")).toBe(true);
  });

  it("injects a style element for hiding", function () {
    loadContentScript(mockHelper);

    var styles = document.head.querySelectorAll("style");
    var found = false;
    for (var i = 0; i < styles.length; i++) {
      if (styles[i].textContent.includes("data-banner-blocker-hidden")) {
        found = true;
        break;
      }
    }
    expect(found).toBe(true);
  });

  it("survives an invalid CSS selector in a banner", function () {
    loadContentScript(mockHelper);

    // Even with a valid banner already processed, an invalid selector
    // in a hypothetical second banner should not crash processBanners.
    // The try/catch in processBanners should skip invalid selectors.
    // We verify the script loaded without throwing.
    expect(document.head.querySelectorAll("style").length).toBeGreaterThan(0);
  });

  describe("MutationObserver", function () {
    it("hides a banner added after initial load", async function () {
      loadContentScript(mockHelper);
      vi.useFakeTimers();

      var el = document.createElement("div");
      el.setAttribute("data-ssr-placeholder", "announcement-banner");
      el.textContent = "Welcome to Atlassian Cloud! To report issues, raise a support ticket here.";
      document.body.appendChild(el);

      // Flush microtasks (MutationObserver callback) then advance debounce timer
      await vi.advanceTimersByTimeAsync(150);
      vi.useRealTimers();

      expect(el.hasAttribute("data-banner-blocker-hidden")).toBe(true);
    });

    it("does not hide non-matching elements added later", async function () {
      loadContentScript(mockHelper);
      vi.useFakeTimers();

      var el = document.createElement("div");
      el.setAttribute("data-ssr-placeholder", "announcement-banner");
      el.textContent = "Some unrelated banner text";
      document.body.appendChild(el);

      await vi.advanceTimersByTimeAsync(150);
      vi.useRealTimers();

      expect(el.hasAttribute("data-banner-blocker-hidden")).toBe(false);
    });

    it("processes multiple banners added in sequence", async function () {
      loadContentScript(mockHelper);
      vi.useFakeTimers();

      // Add two matching elements in rapid succession
      var el1 = document.createElement("div");
      el1.setAttribute("data-ssr-placeholder", "announcement-banner");
      el1.textContent = "Welcome to Atlassian Cloud! First instance.";
      document.body.appendChild(el1);

      var el2 = document.createElement("div");
      el2.setAttribute("data-ssr-placeholder", "announcement-banner");
      el2.textContent = "Welcome to Atlassian Cloud! Second instance.";
      document.body.appendChild(el2);

      await vi.advanceTimersByTimeAsync(150);
      vi.useRealTimers();

      // Both should be hidden after debounced processing
      expect(el1.hasAttribute("data-banner-blocker-hidden")).toBe(true);
      expect(el2.hasAttribute("data-banner-blocker-hidden")).toBe(true);
    });
  });

  describe("storage.onChanged listener", function () {
    it("updates banner visibility when storage changes", function () {
      var el = document.createElement("div");
      el.setAttribute("data-ssr-placeholder", "announcement-banner");
      el.textContent = "Welcome to Atlassian Cloud!";
      document.body.appendChild(el);

      loadContentScript(mockHelper);
      expect(el.hasAttribute("data-banner-blocker-hidden")).toBe(true);

      // Simulate toggling the banner off via popup (writes to storage)
      mockHelper.chrome.storage.local.set({ "atlassian-cloud-welcome": false });

      expect(el.hasAttribute("data-banner-blocker-hidden")).toBe(false);
    });

    it("ignores storage changes for non-banner keys", function () {
      var el = document.createElement("div");
      el.setAttribute("data-ssr-placeholder", "announcement-banner");
      el.textContent = "Welcome to Atlassian Cloud!";
      document.body.appendChild(el);

      loadContentScript(mockHelper);
      expect(el.hasAttribute("data-banner-blocker-hidden")).toBe(true);

      // Simulate a storage change for an unrelated key
      mockHelper.chrome.storage.local.set({ "unrelated-key": true });

      // Banner should still be hidden
      expect(el.hasAttribute("data-banner-blocker-hidden")).toBe(true);
    });

    it("re-enables banner when toggled back on", function () {
      mockHelper.setStore({ "atlassian-cloud-welcome": false });

      var el = document.createElement("div");
      el.setAttribute("data-ssr-placeholder", "announcement-banner");
      el.textContent = "Welcome to Atlassian Cloud!";
      document.body.appendChild(el);

      loadContentScript(mockHelper);
      expect(el.hasAttribute("data-banner-blocker-hidden")).toBe(false);

      // Toggle back on
      mockHelper.chrome.storage.local.set({ "atlassian-cloud-welcome": true });

      expect(el.hasAttribute("data-banner-blocker-hidden")).toBe(true);
    });
  });
});
