// Generated By: Claude Code (Claude Opus 4.6)
import { describe, it, expect, beforeEach } from "vitest";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { createChromeMock } from "./chrome-mock.js";

var dir = path.dirname(fileURLToPath(import.meta.url));
var popupSource = fs.readFileSync(path.resolve(dir, "..", "popup.js"), "utf-8");

function loadPopupScript(chromeMock) {
  globalThis.chrome = chromeMock.chrome;
  var adapted = popupSource.replace(/if \(typeof BANNERS[^}]*\}\s*/, "");
  new Function(adapted)();
}

describe("popup", function () {
  var mockHelper;

  beforeEach(function () {
    mockHelper = createChromeMock();
    document.body.innerHTML = '<div id="banner-list" role="list"></div>';
  });

  it("renders one item per banner", function () {
    loadPopupScript(mockHelper);

    var items = document.querySelectorAll(".banner-item");
    expect(items.length).toBe(BANNERS.length);
  });

  it("renders banner name and description", function () {
    loadPopupScript(mockHelper);

    var name = document.querySelector(".banner-name");
    var desc = document.querySelector(".banner-desc");
    expect(name.textContent).toBe("Atlassian");
    expect(desc.textContent).toContain("Welcome to Atlassian Cloud");
  });

  it("sets checkbox to checked when blocking is enabled (default)", function () {
    loadPopupScript(mockHelper);

    var checkbox = document.querySelector("input[type=checkbox]");
    expect(checkbox.checked).toBe(true);
  });

  it("sets checkbox to unchecked when blocking is disabled in storage", function () {
    mockHelper.setStore({ "atlassian-cloud-welcome": false });
    loadPopupScript(mockHelper);

    var checkbox = document.querySelector("input[type=checkbox]");
    expect(checkbox.checked).toBe(false);
  });

  it("sets aria-label on checkbox", function () {
    loadPopupScript(mockHelper);

    var checkbox = document.querySelector("input[type=checkbox]");
    expect(checkbox.getAttribute("aria-label")).toBe("Block Atlassian");
  });

  it("sets role=listitem on banner items", function () {
    loadPopupScript(mockHelper);

    var item = document.querySelector(".banner-item");
    expect(item.getAttribute("role")).toBe("listitem");
  });

  it("writes to storage when checkbox is toggled", function () {
    loadPopupScript(mockHelper);

    var checkbox = document.querySelector("input[type=checkbox]");
    checkbox.checked = false;
    checkbox.dispatchEvent(new Event("change"));

    var store = mockHelper.getStore();
    expect(store["atlassian-cloud-welcome"]).toBe(false);
  });

  it("reverts checkbox on storage write error", function () {
    loadPopupScript(mockHelper);

    var checkbox = document.querySelector("input[type=checkbox]");
    checkbox.checked = false;
    mockHelper.setLastError({ message: "quota exceeded" });
    checkbox.dispatchEvent(new Event("change"));

    expect(checkbox.checked).toBe(true);
  });

  it("uses defaults when storage read returns an error", function () {
    mockHelper.setLastError({ message: "storage error" });
    loadPopupScript(mockHelper);

    var checkbox = document.querySelector("input[type=checkbox]");
    expect(checkbox.checked).toBe(true);
  });
});
