// Generated By: Claude Code (Claude Opus 4.6)
// Shared test setup — loads banners.js globals into the test environment.

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

var dir = path.dirname(fileURLToPath(import.meta.url));
var source = fs.readFileSync(path.resolve(dir, "..", "banners.js"), "utf-8");

// banners.js declares variables in browser global scope. Evaluate the source
// as-is inside a function, then explicitly capture each export by name.
// Unlike the previous regex approach, this evaluates unmodified source and
// fails with a clear ReferenceError if any export name is removed or renamed.
var exports = {};
var fn = new Function("exports", source + "\n" +
  "exports.BANNERS = BANNERS;\n" +
  "exports.BANNER_IDS = BANNER_IDS;\n" +
  "exports.HIDDEN_ATTR = HIDDEN_ATTR;\n" +
  "exports.getDefaultStates = getDefaultStates;\n" +
  "exports.matchesBanner = matchesBanner;\n" +
  "exports.hideBanner = hideBanner;\n" +
  "exports.showBanner = showBanner;\n" +
  "exports.BB_SHOW_PREFIX = BB_SHOW_PREFIX;\n" +
  "exports.enableBlocking = enableBlocking;\n" +
  "exports.disableBlocking = disableBlocking;\n"
);
fn(exports);
Object.assign(globalThis, exports);
